version: '3.8'
services:
  mysql8:
    build:
      context: ./mysql
    container_name: "${COMPOSE_PROJECT_NAME}_mysql8"
    ports:
      - '3306:3306'
    env_file:
      - ./env/db.env
    volumes:
      - mysql8:/var/lib/mysql

  openid-connect-server:
    build:
      context: ../openid-connect-server
    container_name: "${COMPOSE_PROJECT_NAME}_openid-connect-server"
    command: ../openid-connect-server/run_server.sh
    ports:
      - '3500:3500'
    env_file:
      - ./env/openid.env
    volumes:
      - ../openid-connect-server:/openid-connect-server:cached
      - openid-connect-server_bundle:/usr/local/bundle
      - openid-connect-server_rails_cache:/oauth_manager_server/tmp/cache
    depends_on:
      - mysql8

volumes:
  mysql8:
    driver: local
  openid-connect-server_bundle:
    driver: local
  openid-connect-server_rails_cache:
    driver: local
