version: '3.8'
services:
  mysql8:
    build:
      context: ./mysql
    container_name: "${COMPOSE_PROJECT_NAME}_mysql8"
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - default
  oauth-server:
    build:
      context: ../oauth-server
    container_name: "${COMPOSE_PROJECT_NAME}_oauth-server"
    command: ../oauth-server/run_server.sh
    ports:
      - '3000:3000'
    environment:
      - MYSQL_HOST=mysql8
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    volumes:
      - ../oauth-server:/oauth-server:cached
      - oauth-server-bundle:/usr/local/bundle
      - oauth-server-node_modules:/oauth_manager_server/node_modules
      - oauth-server-packs:/oauth_manager_server/public/packs
      - oauth-server-rails_cache:/oauth_manager_server/tmp/cache
    depends_on:
      - mysql8
    stdin_open: true
    tty: true
    networks:
      - default
    tmpfs:
      - /tmp
volumes:
  oauth-server-bundle:
    driver: local
  oauth-server-node_modules:
    driver: local
  oauth-server-packs:
    driver: local
  oauth-server-rails_cache:
    driver: local
